export const THEMES = [
  { id: "horse-field", label: "Horse in a field", emoji: "\u{1F434}", image: "themes/horse-field.jpg" },
  { id: "football-match", label: "Football match", emoji: "⚽", image: "themes/football-match.jpg" },
  { id: "volcano", label: "Volcano", emoji: "\u{1F30B}", image: "themes/volcano.jpg" },
  { id: "coral-reef", label: "Coral reef", emoji: "\u{1F420}", image: "themes/coral-reef.jpg" },
  { id: "lion-savanna", label: "Lion in the savanna", emoji: "\u{1F981}", image: "themes/lion-savanna.jpg" },
  { id: "wolf-forest", label: "Wolf in the forest", emoji: "\u{1F43A}", image: "themes/wolf-forest.jpg" },
  { id: "owl-night", label: "Owl", emoji: "\u{1F989}", image: "themes/owl-night.jpg" },
  { id: "dolphins-ocean", label: "Dolphins in the ocean", emoji: "\u{1F42C}", image: "themes/dolphins-ocean.jpg" },
  { id: "panda-bamboo", label: "Panda eating bamboo", emoji: "\u{1F43C}", image: "themes/panda-bamboo.jpg" },
  { id: "eagle-mountains", label: "Eagle over mountains", emoji: "\u{1F985}", image: "themes/eagle-mountains.jpg" },
  { id: "fox-snow", label: "Fox in the snow", emoji: "\u{1F98A}", image: "themes/fox-snow.jpg" },
  { id: "elephant-herd", label: "Elephant herd", emoji: "\u{1F418}", image: "themes/elephant-herd.jpg" },
  { id: "butterfly-flower", label: "Butterfly on a flower", emoji: "\u{1F98B}", image: "themes/butterfly-flower.jpg" },
  { id: "penguins-ice", label: "Penguins on ice", emoji: "\u{1F427}", image: "themes/penguins-ice.jpg" },
  { id: "koala-tree", label: "Koala in a tree", emoji: "\u{1F428}", image: "themes/koala-tree.jpg" },
  { id: "tiger-jungle", label: "Tiger in the jungle", emoji: "\u{1F42F}", image: "themes/tiger-jungle.jpg" },
  { id: "giraffes-savanna", label: "Giraffes on the savanna", emoji: "\u{1F992}", image: "themes/giraffes-savanna.jpg" },
  { id: "sea-turtle", label: "Sea turtle", emoji: "\u{1F422}", image: "themes/sea-turtle.jpg" },
  { id: "basketball-court", label: "Basketball court", emoji: "\u{1F3C0}", image: "themes/basketball-court.jpg" },
  { id: "tennis-match", label: "Tennis court", emoji: "\u{1F3BE}", image: "themes/tennis-match.jpg" },
  { id: "surfer-wave", label: "Surfer riding a wave", emoji: "\u{1F3C4}", image: "themes/surfer-wave.jpg" },
  { id: "skier-slope", label: "Skiing on a mountain", emoji: "⛷️", image: "themes/skier-slope.jpg" },
  { id: "cyclist-road", label: "Cycling a mountain road", emoji: "\u{1F6B4}", image: "themes/cyclist-road.jpg" },
  { id: "sailboat-race", label: "Sailboats on the water", emoji: "⛵", image: "themes/sailboat-race.jpg" },
  { id: "northern-lights", label: "Northern lights", emoji: "\u{1F30C}", image: "themes/northern-lights.jpg" },
  { id: "desert-dunes", label: "Desert sand dunes", emoji: "\u{1F3DC}️", image: "themes/desert-dunes.jpg" },
  { id: "rainforest-canopy", label: "Rainforest canopy", emoji: "\u{1F333}", image: "themes/rainforest-canopy.jpg" },
  { id: "mountain-peak", label: "Snow-capped mountain peak", emoji: "\u{1F3D4}️", image: "themes/mountain-peak.jpg" },
  { id: "sunflower-field", label: "Field of sunflowers", emoji: "\u{1F33B}", image: "themes/sunflower-field.jpg" },
  { id: "starry-night", label: "Starry night sky", emoji: "\u{1F320}", image: "themes/starry-night.jpg" },
  { id: "full-moon-ocean", label: "Full moon over the ocean", emoji: "\u{1F315}", image: "themes/full-moon-ocean.jpg" },
  { id: "rainbow", label: "Rainbow", emoji: "\u{1F308}", image: "themes/rainbow.jpg" },
  { id: "lightning-storm", label: "Lightning storm", emoji: "⚡", image: "themes/lightning-storm.jpg" },
  { id: "tropical-beach", label: "Tropical beach", emoji: "\u{1F334}", image: "themes/tropical-beach.jpg" },
  { id: "autumn-forest", label: "Forest in autumn color", emoji: "\u{1F341}", image: "themes/autumn-forest.jpg" },
  { id: "desert-cactus", label: "Desert cactus", emoji: "\u{1F335}", image: "themes/desert-cactus.jpg" },
  { id: "pizza", label: "Pizza", emoji: "\u{1F355}", image: "themes/pizza.jpg" },
  { id: "sushi", label: "Sushi", emoji: "\u{1F363}", image: "themes/sushi.jpg" },
  { id: "ice-cream", label: "Ice cream", emoji: "\u{1F366}", image: "themes/ice-cream.jpg" },
  { id: "croissant-coffee", label: "Croissant and coffee", emoji: "\u{1F950}", image: "themes/croissant-coffee.jpg" },
  { id: "tropical-fruit", label: "Tropical fruit", emoji: "\u{1F34D}", image: "themes/tropical-fruit.jpg" },
  { id: "paris-eiffel", label: "Paris, Eiffel Tower", emoji: "\u{1F5FC}", image: "themes/paris-eiffel.jpg" },
  { id: "nyc-skyline", label: "New York City skyline", emoji: "\u{1F3D9}️", image: "themes/nyc-skyline.jpg" },
  { id: "torii-gate", label: "Japanese torii gate", emoji: "⛩️", image: "themes/torii-gate.jpg" },
  { id: "castle-hill", label: "Castle on a hill", emoji: "\u{1F3F0}", image: "themes/castle-hill.jpg" },
  { id: "venice-canal", label: "Venice canal", emoji: "\u{1F6F6}", image: "themes/venice-canal.jpg" },
  { id: "fireworks-city", label: "Fireworks over a city", emoji: "\u{1F386}", image: "themes/fireworks-city.jpg" },
  { id: "cat-window", label: "Cat by a window", emoji: "\u{1F431}", image: "themes/cat-window.jpg" },
  { id: "dog-beach", label: "Dog running on a beach", emoji: "\u{1F436}", image: "themes/dog-beach.jpg" },
  { id: "carousel", label: "Carousel at a fairground", emoji: "\u{1F3A0}", image: "themes/carousel.jpg" },
];

export function getRandomTheme() {
  const index = Math.floor(Math.random() * THEMES.length);
  return THEMES[index];
}
